name: 'AI Code Review'
description: 'Post OpenAI-generated review comments on PR diff'
author: 'ucan-lab'
inputs:
  openai_api_key:
    description: 'OpenAI API Key'
    required: true
  prompt_file:
    description: 'カスタムプロンプトファイルのパス'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
