name: Assign Author
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  assign-author:
    if: ${{ ! contains(fromJson('["renovate[bot]", "dependabot[bot]"]'), github.actor) }}
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to issue
        if: github.event_name == 'issues'
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees \
            -d '{"assignees":["${{ github.event.issue.user.login }}"]}'
      - name: Assign author to pull request
        if: github.event_name == 'pull_request'
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees \
            -d '{"assignees":["${{ github.event.pull_request.user.login }}"]}'
